# -*- coding: utf-8 -*-
"""M22MA207.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10W06tWd58RjWZLMh9HoAN59PoD7_8JP6
"""

from google.colab import drive
drive.mount('/content/drive')

import zipfile

zip_path ='/content/drive/MyDrive/archive (3).zip'
extract_to = "/content/fer2013"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_to)

print("✅ Dataset extracted to:", extract_to)

import os
import shutil

# Emotion categories grouped into binary labels
emotion_to_binary = {
    'angry': 'stress',
    'disgust': 'stress',
    'fear': 'stress',
    'sad': 'stress',
    'happy': 'non_stress',
    'neutral': 'non_stress',
    'surprise': 'non_stress'
}

# Original dataset path and destination path
input_dataset_path = "/content/fer2013"
output_dataset_path = "/content/fer2013_binary"

# Create new folder structure for binary classification
splits = ['train', 'test']
binary_labels = ['stress', 'non_stress']

for split in splits:
    for label in binary_labels:
        os.makedirs(os.path.join(output_dataset_path, split, label), exist_ok=True)

# Function to copy and relabel images
def convert_to_binary_labels(split_name):
    original_split_path = os.path.join(input_dataset_path, split_name)
    if not os.path.exists(original_split_path):
        print(f"Skipping {split_name}: directory does not exist.")
        return

    for emotion_label in os.listdir(original_split_path):
        emotion_dir = os.path.join(original_split_path, emotion_label)
        if not os.path.isdir(emotion_dir):
            continue

        binary_label = emotion_to_binary.get(emotion_label)
        if binary_label is None:
            continue

        for filename in os.listdir(emotion_dir):
            source_file = os.path.join(emotion_dir, filename)
            destination_file = os.path.join(output_dataset_path, split_name, binary_label, filename)
            shutil.copy(source_file, destination_file)

# Apply relabeling for training and test sets
convert_to_binary_labels('train')
convert_to_binary_labels('test')

print("Binary relabeling completed successfully.")

from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Data path that matches output from the relabeling step
binary_data_dir = '/content/fer2013_binary'

# Data generator with augmentation for training subset
augmented_train_gen = ImageDataGenerator(
    rescale=1.0 / 255,
    rotation_range=15,
    zoom_range=0.1,
    horizontal_flip=True,
    validation_split=0.2
)

# Generator without augmentation for testing
standard_test_gen = ImageDataGenerator(rescale=1.0 / 255)

# Load actual training subset
train_data_loader = augmented_train_gen.flow_from_directory(
    directory=os.path.join(binary_data_dir, 'train'),
    target_size=(48, 48),
    color_mode='grayscale',
    batch_size=64,
    class_mode='binary',
    subset='training'
)

# Load validation subset from training folder
validation_data_loader = augmented_train_gen.flow_from_directory(
    directory=os.path.join(binary_data_dir, 'train'),
    target_size=(48, 48),
    color_mode='grayscale',
    batch_size=64,
    class_mode='binary',
    subset='validation'
)

# Load testing data
test_data_loader = standard_test_gen.flow_from_directory(
    directory=os.path.join(binary_data_dir, 'test'),
    target_size=(48, 48),
    color_mode='grayscale',
    batch_size=64,
    class_mode='binary',
    shuffle=False
)

import os

# Define splits and binary categories
dataset_splits = ['train', 'test', 'validation']
binary_categories = ['stress', 'non_stress']
data_root_path = '/content/fer2013_binary'

# Display number of images per category in each split
for split_name in dataset_splits:
    for category in binary_categories:
        category_path = os.path.join(data_root_path, split_name, category)
        if os.path.exists(category_path):
            num_files = len(os.listdir(category_path))
            print(f"{split_name}/{category}: {num_files} samples found")
        else:
            print(f"Directory does not exist: {category_path}")

import numpy as np

# Define sequence configuration
SEQUENCE_LENGTH = 10
INPUT_IMAGE_SHAPE = (48, 48, 1)

def create_frame_sequences(data_loader, max_batches):
    sequences_X, sequences_y = [], []
    batch_counter = 0

    for images, labels in data_loader:
        for idx in range(0, len(images) - SEQUENCE_LENGTH + 1, SEQUENCE_LENGTH):
            sequence = images[idx:idx + SEQUENCE_LENGTH]
            if sequence.shape[0] == SEQUENCE_LENGTH:
                sequences_X.append(sequence)
                sequences_y.append(labels[idx])
        batch_counter += 1
        if batch_counter >= max_batches:
            break

    return np.array(sequences_X), np.array(sequences_y)

# Generate sequences from data loaders
X_train_seq, y_train_seq = create_frame_sequences(train_data_loader, max_batches=360)
X_val_seq, y_val_seq     = create_frame_sequences(validation_data_loader, max_batches=90)
X_test_seq, y_test_seq   = create_frame_sequences(test_data_loader, max_batches=113)

import tensorflow as tf
from tensorflow.keras.layers import Layer

class SequenceAttentionLayer(tf.keras.layers.Layer):
    def __init__(self):
        super(SequenceAttentionLayer, self).__init__()

    def build(self, input_shape):
        feature_dim = input_shape[-1]
        time_steps = input_shape[1]

        # Learnable weight and bias for attention scoring
        self.attention_weights = self.add_weight(
            name="weights",
            shape=(feature_dim, 1),
            initializer="random_normal",
            trainable=True
        )
        self.attention_bias = self.add_weight(
            name="bias",
            shape=(time_steps, 1),
            initializer="zeros",
            trainable=True
        )

    def call(self, inputs):
        # inputs shape: (batch_size, time_steps, features)
        attention_logits = tf.nn.tanh(tf.tensordot(inputs, self.attention_weights, axes=1) + self.attention_bias)
        attention_scores = tf.nn.softmax(attention_logits, axis=1)
        attended_output = tf.reduce_sum(inputs * attention_scores, axis=1)
        return attended_output

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (Input, Lambda, Dropout, Dense, ConvLSTM2D,
                                     GlobalAveragePooling2D)
from tensorflow.keras.applications import MobileNetV2

# Custom temporal attention mechanism
class SequenceAttentionLayer(tf.keras.layers.Layer):
    def __init__(self):
        super(SequenceAttentionLayer, self).__init__()

    def build(self, input_shape):
        self.attention_weight = self.add_weight(
            name="attention_weight",
            shape=(input_shape[-1], 1),
            initializer="random_normal",
            trainable=True
        )
        self.attention_bias = self.add_weight(
            name="attention_bias",
            shape=(input_shape[1], 1),
            initializer="zeros",
            trainable=True
        )

    def call(self, inputs):
        attention_logits = tf.nn.tanh(tf.tensordot(inputs, self.attention_weight, axes=1) + self.attention_bias)
        attention_weights = tf.nn.softmax(attention_logits, axis=1)
        weighted_sum = tf.reduce_sum(inputs * attention_weights, axis=1)
        return weighted_sum

# Full model architecture
def build_stress_detection_model(sequence_length=10, input_shape=(48, 48, 1)):
    sequence_input = Input(shape=(sequence_length, *input_shape))

    # Convert grayscale to RGB for compatibility with MobileNetV2
    def grayscale_to_rgb(batch_tensor):
        reshaped = tf.reshape(batch_tensor, (-1, 48, 48, 1))
        return tf.image.grayscale_to_rgb(reshaped)

    rgb_input = Lambda(grayscale_to_rgb)(sequence_input)

    # MobileNetV2 pretrained CNN encoder
    cnn_encoder = MobileNetV2(input_shape=(48, 48, 3), include_top=False, weights='imagenet')
    cnn_encoder.trainable = False
    features = cnn_encoder(rgb_input)
    pooled_features = GlobalAveragePooling2D()(features)

    # Reshape features to sequence format for ConvLSTM2D
    reshaped_sequence = Lambda(lambda x: tf.reshape(x, (-1, sequence_length, 1, 1280, 1)))(pooled_features)

    # Temporal modeling using ConvLSTM2D
    conv_lstm_output = ConvLSTM2D(filters=64, kernel_size=(1, 3), return_sequences=True)(reshaped_sequence)
    squeezed = Lambda(lambda x: tf.squeeze(x, axis=2))(conv_lstm_output)
    averaged_features = Lambda(lambda x: tf.reduce_mean(x, axis=2))(squeezed)

    # Apply temporal attention to focus on important frames
    context_vector = SequenceAttentionLayer()(averaged_features)

    # Fully connected classification layers
    x = Dropout(0.5)(context_vector)
    x = Dense(64, activation='relu')(x)
    x = Dropout(0.3)(x)
    output = Dense(1, activation='sigmoid')(x)

    return Model(sequence_input, output)

stress_model = build_stress_detection_model()

stress_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

stress_model.summary()

import os
import cv2
import numpy as np
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

def prepare_sequence_dataset(root_path, sequence_length=10):
    sequences = []
    labels = []

    category_map = {'non_stress': 0, 'stress': 1}

    for class_name, class_label in category_map.items():
        class_path = os.path.join(root_path, class_name)
        image_files = sorted(os.listdir(class_path))
        image_files = shuffle(image_files)

        for start_idx in range(0, len(image_files) - sequence_length + 1, sequence_length):
            sequence_frames = []
            for offset in range(sequence_length):
                image_path = os.path.join(class_path, image_files[start_idx + offset])
                image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
                resized_image = cv2.resize(image, (48, 48))
                normalized = resized_image / 255.0
                sequence_frames.append(normalized)
            sequences.append(sequence_frames)
            labels.append(class_label)

    return np.array(sequences)[..., np.newaxis], np.array(labels)

# Load training and testing sequences
X_train_full, y_train_full = prepare_sequence_dataset('/content/fer2013_binary/train')
X_test, y_test = prepare_sequence_dataset('/content/fer2013_binary/test')

# Split part of training data for validation
X_train, X_val, y_train, y_val = train_test_split(
    X_train_full, y_train_full, test_size=0.2, random_state=42, stratify=y_train_full
)

# Display dataset dimensions
print("Sequence Dataset Dimensions:")
print("Training Set   :", X_train.shape, y_train.shape)
print("Validation Set :", X_val.shape, y_val.shape)
print("Test Set       :", X_test.shape, y_test.shape)

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

# Model compilation
stress_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Defining the callbacks
callbacks = [
    EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True, verbose=1),
    ModelCheckpoint("best_model.h5", save_best_only=True, monitor='val_loss', verbose=1),
    ReduceLROnPlateau(monitor='val_loss', factor=0.3, patience=3, verbose=1)
]

# Model training
history = stress_model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=30,
    batch_size=32,
    callbacks=callbacks
)

# Evaluate the model on the test dataset
test_loss, test_accuracy = stress_model.evaluate(X_test, y_test)

# Display the evaluation results
print(f"Test Accuracy: {test_accuracy:.4f}, Test Loss: {test_loss:.4f}")

# Save the trained model weights to a file
stress_model.save_weights("best_temporal_model_v2.weights.h5")

import os
import zipfile
import random
import shutil
from PIL import Image
import cv2

# Define source directories and output path
stress_src = "/content/fer2013_binary/train/stress"
nonstress_src = "/content/fer2013_binary/train/non_stress"
eval_out = "/content/eval_set"

# Clear existing evaluation directory if it exists
if os.path.exists(eval_out):
    shutil.rmtree(eval_out)

# Create directories for evaluation output
os.makedirs(os.path.join(eval_out, "stress"), exist_ok=True)
os.makedirs(os.path.join(eval_out, "non_stress"), exist_ok=True)

# Function to generate zipped evaluation sets
def create_eval_zip(src_dir, label, num_archives=5):
    for i in range(num_archives):
        selected_images = random.sample(os.listdir(src_dir), 10)
        zip_path = os.path.join(eval_out, label, f"{label}_{i}.zip")
        with zipfile.ZipFile(zip_path, 'w') as zipf:
            for idx, img_name in enumerate(selected_images):
                img_path = os.path.join(src_dir, img_name)
                image = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
                image = cv2.resize(image, (48, 48))
                temp_filename = f"{label}_{i}_{idx}.png"
                temp_path = os.path.join("/tmp", temp_filename)
                Image.fromarray(image).save(temp_path)
                zipf.write(temp_path, arcname=temp_filename)
                os.remove(temp_path)

# Generate evaluation archives for both classes
create_eval_zip(stress_src, "stress", num_archives=5)
create_eval_zip(nonstress_src, "non_stress", num_archives=5)

print("Evaluation set has been successfully generated.")

import zipfile
import os
import cv2
import numpy as np
import shutil
from PIL import Image

def evaluate_accuracy_on_folder(folder_path, threshold=0.6):
    correct_predictions = 0
    total_samples = 0
    misclassified_cases = []

    for class_name in ["stress", "non_stress"]:
        class_path = os.path.join(folder_path, class_name)
        true_label = 1 if class_name == "stress" else 0

        for zip_filename in sorted(os.listdir(class_path)):
            if not zip_filename.endswith(".zip"):
                continue

            zip_path = os.path.join(class_path, zip_filename)
            temp_dir = "/content/temp_eval"

            if os.path.exists(temp_dir):
                shutil.rmtree(temp_dir)
            os.makedirs(temp_dir, exist_ok=True)

            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                zip_ref.extractall(temp_dir)

            image_files = sorted([f for f in os.listdir(temp_dir) if f.endswith(".png")])[:10]
            frames = [cv2.imread(os.path.join(temp_dir, f)) for f in image_files]

            sequence = []
            for frame in frames:
                gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
                resized = cv2.resize(gray, (48, 48)).astype("float32") / 255.0
                resized = np.expand_dims(resized, axis=-1)
                sequence.append(resized)

            sequence_array = np.expand_dims(np.stack(sequence), axis=0)
            prediction_prob = stress_model.predict(sequence_array)[0][0]
            predicted_label = 1 if prediction_prob > threshold else 0

            if predicted_label == true_label:
                correct_predictions += 1
            else:
                misclassified_cases.append((zip_filename, class_name, prediction_prob))

            total_samples += 1

    # Summary of results
    accuracy = 100 * correct_predictions / total_samples
    print(f"Evaluation Completed: Accuracy = {accuracy:.2f}% ({correct_predictions}/{total_samples})")

    if misclassified_cases:
        print("\nMisclassified Samples:")
        for filename, actual_label, probability in misclassified_cases:
            predicted_class = "stress" if probability > threshold else "non_stress"
            print(f" - {filename} | Actual: {actual_label}, Predicted: {predicted_class} (Confidence: {probability:.2f})")

stress_model.load_weights("best_temporal_model_v2.weights.h5")
evaluate_accuracy_on_folder("/content/eval_set")

import matplotlib.pyplot as plt

# Plotting training and validation accuracy
plt.figure(figsize=(8, 5))
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title("Model Accuracy Over Epochs")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Plotting training and validation loss
plt.figure(figsize=(8, 5))
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title("Model Loss Over Epochs")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Generate predictions on the test sequences
y_pred = stress_model.predict(X_test_seq)
y_pred_classes = (y_pred > 0.5).astype(int)

# Display classification performance metrics
print(classification_report(
    y_test_seq,
    y_pred_classes,
    target_names=["non_stress", "stress"]
))

# Compute confusion matrix
cm = confusion_matrix(y_test_seq, y_pred_classes)

# Plot confusion matrix
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["non_stress", "stress"],
            yticklabels=["non_stress", "stress"])
plt.title("Confusion Matrix - Test Data")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.tight_layout()
plt.show()

import tensorflow as tf

@tf.keras.utils.register_keras_serializable()
class TemporalAttention(tf.keras.layers.Layer):
    def __init__(self, return_attention=False, **kwargs):
        super().__init__(**kwargs)
        self.return_attention = return_attention

    def build(self, input_shape):
        feature_dim = input_shape[-1]
        time_steps = input_shape[1]
        self.W = self.add_weight(
            name="attention_weight",
            shape=(feature_dim, 1),
            initializer="random_normal",
            trainable=True
        )
        self.b = self.add_weight(
            name="attention_bias",
            shape=(time_steps, 1),
            initializer="zeros",
            trainable=True
        )

    def call(self, inputs):
        # Compute attention scores
        attention_scores = tf.nn.tanh(tf.tensordot(inputs, self.W, axes=1) + self.b)
        attention_weights = tf.nn.softmax(attention_scores, axis=1)

        # Apply attention weights to input
        weighted_output = tf.reduce_sum(inputs * attention_weights, axis=1)

        if self.return_attention:
            return weighted_output, attention_weights
        return weighted_output

from tensorflow.keras.models import Model
from tensorflow.keras.layers import (Input, Lambda, TimeDistributed, GlobalAveragePooling2D,
                                     ConvLSTM2D, Dropout, Dense)
from tensorflow.keras.applications import MobileNetV2
import tensorflow as tf

def build_temporal_model_with_attention():
    # Define input with shape corresponding to a sequence of grayscale frames
    input_layer = Input(shape=(10, 48, 48, 1), name="input_layer")

    # Convert grayscale to 3-channel RGB format for MobileNetV2 compatibility
    rgb_input = Lambda(lambda x: tf.repeat(x, repeats=3, axis=-1))(input_layer)

    # Use MobileNetV2 as the feature extractor (frozen)
    backbone = MobileNetV2(input_shape=(48, 48, 3), include_top=False, weights='imagenet')
    backbone.trainable = False

    # Apply CNN backbone to each frame
    features = TimeDistributed(backbone)(rgb_input)
    features = TimeDistributed(GlobalAveragePooling2D())(features)

    # Prepare input format for ConvLSTM2D
    features = Lambda(lambda x: tf.expand_dims(x, axis=2))(features)
    features = Lambda(lambda x: tf.expand_dims(x, axis=-1))(features)

    # Capture temporal patterns using ConvLSTM2D
    x = ConvLSTM2D(64, kernel_size=(1, 3), padding='same', return_sequences=True)(features)
    x = Lambda(lambda x: tf.squeeze(x, axis=2))(x)
    x = Lambda(lambda x: tf.reduce_mean(x, axis=2))(x)

    # Apply temporal attention mechanism
    attention_output, attention_weights = TemporalAttention(return_attention=True, name="temporal_attention")(x)

    # Classification head
    x = Dropout(0.3)(attention_output)
    x = Dense(64, activation='relu')(x)
    x = Dropout(0.3)(x)
    output = Dense(1, activation='sigmoid')(x)

    # Construct and return the model
    return Model(inputs=input_layer, outputs=[output, attention_weights])

# Load the model with attention mechanism
model_with_attention = build_temporal_model_with_attention()
model_with_attention.load_weights("best_model.h5")
print("Attention model has been loaded successfully!")

import numpy as np
import matplotlib.pyplot as plt

# Ensure old variable is removed if it exists
try:
    del sample_rgb
except NameError:
    pass

# Function to convert grayscale to RGB (used for visualization purposes, not prediction)
def convert_to_rgb(x):
    if x.shape[-1] == 1:
        return np.concatenate([x] * 3, axis=-1)
    elif x.shape[-1] == 3:
        return x  # Already in RGB format
    else:
        raise ValueError(f"Expected 1 or 3 channels, but got {x.shape[-1]}")

# Select a random sample from the test set
idx = np.random.randint(len(X_test_seq))
sample = X_test_seq[idx:idx+1]  # Shape: (1, 10, 48, 48, 1)

# Convert the sample to RGB for visualization
sample_rgb = convert_to_rgb(sample)

# Print the shapes of the sample and converted RGB sample
print("Shape of sample:", sample.shape)
print("Shape of sample_rgb:", sample_rgb.shape)
print("Channels in sample_rgb:", sample_rgb.shape[-1])  # Should be 3

# Make a prediction using the model (works with grayscale as model handles RGB conversion internally)
output, attention_scores = model_with_attention.predict(sample)
attention_scores = attention_scores.squeeze()

# Visualize the frames with their attention scores
plt.figure(figsize=(15, 3))
for i in range(10):
    plt.subplot(1, 10, i + 1)
    plt.imshow(sample[0, i].squeeze(), cmap='gray')
    plt.title(f"{attention_scores[i]:.2f}")
    plt.axis("off")
plt.suptitle("Frame Importance Based on Temporal Attention", fontsize=16)
plt.tight_layout()
plt.show()

import numpy as np
import os
from tqdm import tqdm

# Create an output directory to store the results
os.makedirs("attention_outputs", exist_ok=True)

# Initialize lists to store attention scores, predictions, and labels
all_attention_scores = []
all_predictions = []
all_labels = []

# Loop through the test sequences to extract attention scores
for i in tqdm(range(len(X_test_seq)), desc="Extracting attention"):
    sample = X_test_seq[i:i+1]
    label = y_test_seq[i]

    # Predict the output and attention scores for the current sample
    output, attention = model_with_attention.predict(sample, verbose=0)

    # Append the attention scores, predictions, and labels
    all_attention_scores.append(attention.squeeze())
    all_predictions.append(output.squeeze())
    all_labels.append(label)

# Convert lists to numpy arrays for further processing
all_attention_scores = np.array(all_attention_scores)
all_predictions = np.array(all_predictions)
all_labels = np.array(all_labels)

# Save the results to files
np.save("attention_outputs/all_attention_scores.npy", all_attention_scores)
np.save("attention_outputs/all_predictions.npy", all_predictions)
np.save("attention_outputs/all_labels.npy", all_labels)

print("All attention scores, predictions, and labels have been saved successfully!")

import numpy as np
import matplotlib.pyplot as plt

# Load
attention_scores = np.load("attention_outputs/all_attention_scores.npy")
predictions = np.load("attention_outputs/all_predictions.npy")
labels = np.load("attention_outputs/all_labels.npy")
# Separate the attention scores by class (stress vs. non-stress)
stress_scores = attention_scores[labels == 1]
non_stress_scores = attention_scores[labels == 0]

# Calculate the average attention scores per frame for each class
avg_stress = np.mean(stress_scores, axis=0)
avg_non_stress = np.mean(non_stress_scores, axis=0)

# Plot the average attention scores
plt.figure(figsize=(10, 5))
plt.plot(avg_stress, label='Stress', marker='o', color='red')
plt.plot(avg_non_stress, label='Non-Stress', marker='o', color='green')
plt.title("Average Frame-wise Attention: Stress vs Non-Stress")
plt.xlabel("Frame Index")
plt.ylabel("Average Attention Score")
plt.xticks(ticks=np.arange(10), labels=[f"F{i}" for i in range(10)])
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import os
import zipfile
import shutil
import random
from PIL import Image

# Define the source and output directories
src_stress_dir = "/content/fer2013_binary/train/stress"
src_nonstress_dir = "/content/fer2013_binary/train/non_stress"
output_dir = "/content/test_faces"
zip_path = "/content/test_faces.zip"

# Create the output directory if it doesn't exist
os.makedirs(output_dir, exist_ok=True)

# Select 5 random images from each class
stress_imgs = random.sample(os.listdir(src_stress_dir), 5)
nonstress_imgs = random.sample(os.listdir(src_nonstress_dir), 5)

# Copy and resize images to the output directory
for i, fname in enumerate(stress_imgs):
    src = os.path.join(src_stress_dir, fname)
    dst = os.path.join(output_dir, f"stress_{i}.png")
    img = Image.open(src).convert("L").resize((48, 48))
    img.save(dst)

for i, fname in enumerate(nonstress_imgs):
    src = os.path.join(src_nonstress_dir, fname)
    dst = os.path.join(output_dir, f"nonstress_{i}.png")
    img = Image.open(src).convert("L").resize((48, 48))
    img.save(dst)

# Compress the images into a ZIP file
with zipfile.ZipFile(zip_path, "w") as zipf:
    for fname in sorted(os.listdir(output_dir)):
        fpath = os.path.join(output_dir, fname)
        zipf.write(fpath, arcname=fname)

print(f"Successfully created ZIP file: {zip_path}")

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Lambda, TimeDistributed, GlobalAveragePooling2D, ConvLSTM2D, Dropout, Dense
from tensorflow.keras.applications import MobileNetV2

# Define a custom layer for Temporal Attention
@tf.keras.utils.register_keras_serializable()
class TemporalAttention(tf.keras.layers.Layer):
    def __init__(self, return_attention=False, **kwargs):
        super(TemporalAttention, self).__init__(**kwargs)
        self.return_attention = return_attention

    def build(self, input_shape):
        # Initialize weights for attention mechanism
        self.W = self.add_weight(name="att_weight", shape=(input_shape[-1], 1),
                                 initializer="random_normal", trainable=True)
        self.b = self.add_weight(name="att_bias", shape=(input_shape[1], 1),
                                 initializer="zeros", trainable=True)

    def call(self, inputs):
        # Calculate attention scores
        e = tf.nn.tanh(tf.tensordot(inputs, self.W, axes=1) + self.b)
        alpha = tf.nn.softmax(e, axis=1)
        # Calculate context vector
        context = tf.reduce_sum(inputs * alpha, axis=1)
        if self.return_attention:
            return context, alpha
        return context

# Function to build the temporal model with attention
def build_temporal_model_with_attention():
    input_layer = Input(shape=(10, 48, 48, 1), name="input_layer")
    # Replicate input channels to match MobileNetV2 input shape
    x = Lambda(lambda x: tf.repeat(x, repeats=3, axis=-1))(input_layer)

    # Use MobileNetV2 as base model with pretrained weights
    base_cnn = MobileNetV2(input_shape=(48, 48, 3), include_top=False, weights='imagenet')
    base_cnn.trainable = False
    x = TimeDistributed(base_cnn)(x)
    x = TimeDistributed(GlobalAveragePooling2D())(x)

    # Apply ConvLSTM2D for sequential feature extraction
    x = Lambda(lambda x: tf.expand_dims(x, axis=2))(x)
    x = Lambda(lambda x: tf.expand_dims(x, axis=-1))(x)
    x = ConvLSTM2D(64, kernel_size=(1, 3), padding='same', return_sequences=True)(x)

    # Reduce sequence dimension and take average
    x = Lambda(lambda x: tf.squeeze(x, axis=2))(x)
    x = Lambda(lambda x: tf.reduce_mean(x, axis=2))(x)

    # Apply temporal attention
    context, alpha = TemporalAttention(return_attention=True, name="temporal_attention")(x)

    # Add dropout and dense layers for classification
    x = Dropout(0.3)(context)
    x = Dense(64, activation='relu')(x)
    x = Dropout(0.3)(x)
    output = Dense(1, activation='sigmoid')(x)

    return Model(inputs=input_layer, outputs=[output, alpha])

# Save the model code to a file
code = '''
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Lambda, TimeDistributed, GlobalAveragePooling2D, ConvLSTM2D, Dropout, Dense
from tensorflow.keras.applications import MobileNetV2

@tf.keras.utils.register_keras_serializable()
class TemporalAttention(tf.keras.layers.Layer):
    def __init__(self, return_attention=False, **kwargs):
        super(TemporalAttention, self).__init__(**kwargs)
        self.return_attention = return_attention

    def build(self, input_shape):
        self.W = self.add_weight(name="att_weight", shape=(input_shape[-1], 1),
                                 initializer="random_normal", trainable=True)
        self.b = self.add_weight(name="att_bias", shape=(input_shape[1], 1),
                                 initializer="zeros", trainable=True)

    def call(self, inputs):
        e = tf.nn.tanh(tf.tensordot(inputs, self.W, axes=1) + self.b)
        alpha = tf.nn.softmax(e, axis=1)
        context = tf.reduce_sum(inputs * alpha, axis=1)
        if self.return_attention:
            return context, alpha
        return context

def build_temporal_model_with_attention():
    input_layer = Input(shape=(10, 48, 48, 1), name="input_layer")
    x = Lambda(lambda x: tf.repeat(x, repeats=3, axis=-1))(input_layer)
    base_cnn = MobileNetV2(input_shape=(48, 48, 3), include_top=False, weights='imagenet')
    base_cnn.trainable = False
    x = TimeDistributed(base_cnn)(x)
    x = TimeDistributed(GlobalAveragePooling2D())(x)
    x = Lambda(lambda x: tf.expand_dims(x, axis=2))(x)
    x = Lambda(lambda x: tf.expand_dims(x, axis=-1))(x)
    x = ConvLSTM2D(64, kernel_size=(1, 3), padding='same', return_sequences=True)(x)
    x = Lambda(lambda x: tf.squeeze(x, axis=2))(x)
    x = Lambda(lambda x: tf.reduce_mean(x, axis=2))(x)
    context, alpha = TemporalAttention(return_attention=True, name="temporal_attention")(x)
    x = Dropout(0.3)(context)
    x = Dense(64, activation='relu')(x)
    x = Dropout(0.3)(x)
    output = Dense(1, activation='sigmoid')(x)
    return Model(inputs=input_layer, outputs=[output, alpha])
'''

# Write code to file
with open("temporal_model.py", "w") as f:
    f.write(code)

print("Model code saved to 'temporal_model.py'.")

from temporal_model import build_temporal_model_with_attention

# Build the temporal model with attention mechanism
model = build_temporal_model_with_attention()

# Load the pretrained weights for the model (ensure the file exists in the directory)
model.load_weights("best_model.h5")

import numpy as np

# Generate a dummy sequence consisting of 10 grayscale 48x48 images with pixel values between 0 and 1
sequence = np.random.rand(1, 10, 48, 48, 1).astype(np.float32)

# Make a prediction using the model
outputs = model.predict(sequence)

# Extract the prediction and attention scores from the outputs
if isinstance(outputs, list) and len(outputs) == 2:
    prediction, attention = outputs
else:
    prediction = outputs
    attention = np.ones((1, 10, 1))  # Default fallback if attention is not returned

# Display the prediction and attention scores
print("Prediction:", prediction)
print("Attention scores:", attention)

from PIL import Image
import cv2
import numpy as np

def preprocess_video_frames(video_path):
    # Open the video file using OpenCV
    cap = cv2.VideoCapture(video_path)
    frames = []

    # Extract the first 10 frames from the video
    while len(frames) < 10:
        ret, frame = cap.read()
        if not ret:
            break
        # Resize the frame to 48x48 and convert to grayscale
        frame = cv2.resize(frame, (48, 48))
        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        # Normalize pixel values
        gray_frame = gray_frame.astype('float32') / 255.0
        frames.append(gray_frame)

    cap.release()

    # If there are fewer than 10 frames, pad the list with the last frame
    while len(frames) < 10:
        frames.append(frames[-1])

    frames = np.array(frames).reshape(1, 10, 48, 48, 1)
    return frames

# Preprocess the video frames from the specified video file
sequence = preprocess_video_frames("/content/drive/MyDrive/8196796-hd_1920_1080_25fps.mp4")

# Make a prediction using the model
outputs = model.predict(sequence)

import matplotlib.pyplot as plt
import cv2
import numpy as np

def preprocess_video_with_frames(video_path):
    cap = cv2.VideoCapture(video_path)
    frames = []

    while len(frames) < 10:
        ret, frame = cap.read()
        if not ret:
            break
        frame_resized = cv2.resize(frame, (48, 48))
        gray_frame = cv2.cvtColor(frame_resized, cv2.COLOR_BGR2GRAY)
        normalized_gray = gray_frame.astype('float32') / 255.0
        frames.append(normalized_gray)

    cap.release()

    if len(frames) == 0:
        raise ValueError("Unable to read frames from the video. Please check the video file.")

    while len(frames) < 10:
        frames.append(frames[-1])

    input_tensor = np.array(frames).reshape(1, 10, 48, 48, 1)
    return input_tensor, frames

sequence, raw_frames = preprocess_video_with_frames("/content/drive/MyDrive/8196796-hd_1920_1080_25fps.mp4")
prediction, attention = model.predict(sequence)

plt.figure(figsize=(15, 5))
for i in range(10):
    plt.subplot(2, 5, i + 1)
    plt.imshow(raw_frames[i], cmap='gray')
    plt.title(f"Attn: {attention[0][i][0]:.2f}")
    plt.axis('off')

plt.suptitle(f"Frame-wise Attention ({label})", fontsize=16)
plt.tight_layout()
plt.show()

!pip install gradio --quiet

from temporal_model import build_temporal_model_with_attention
model = build_temporal_model_with_attention()
model.load_weights("best_model.h5")

import os
import cv2
import zipfile
import shutil
import tempfile
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import gradio as gr

from temporal_model import build_temporal_model_with_attention

model = build_temporal_model_with_attention()
model.load_weights("best_model.h5")

def prepare_sequence(frames):
    processed_frames = []
    for frame in frames:
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        resized = cv2.resize(gray, (48, 48))
        normalized = resized.astype("float32") / 255.0
        processed_frames.append(np.expand_dims(normalized, axis=-1))
    return np.expand_dims(np.stack(processed_frames), axis=0)

def get_frames_from_video(video_path):
    cap = cv2.VideoCapture(video_path)
    frames = []
    while len(frames) < 10:
        ret, frame = cap.read()
        if not ret:
            break
        frames.append(frame)
    cap.release()
    while len(frames) < 10 and frames:
        frames.append(frames[-1])
    return frames[:10]

def extract_images_from_zip(zip_file):
    temp_dir = tempfile.mkdtemp()
    with zipfile.ZipFile(zip_file, 'r') as archive:
        archive.extractall(temp_dir)
    image_files = sorted([
        f for f in os.listdir(temp_dir)
        if f.lower().endswith(('.png', '.jpg', '.jpeg'))
    ])[:10]
    images = [cv2.imread(os.path.join(temp_dir, f)) for f in image_files]
    shutil.rmtree(temp_dir)
    return images

def replicate_image(image_path):
    image = cv2.imread(image_path.name if hasattr(image_path, 'name') else image_path)
    return [image] * 10

def evaluate_input(file):
    ext = os.path.splitext(file.name if hasattr(file, "name") else file)[-1].lower()

    if ext == ".zip":
        frames = extract_images_from_zip(file)
    elif ext in [".mp4", ".mov", ".avi"]:
        frames = get_frames_from_video(file)
    elif ext in [".png", ".jpg", ".jpeg"]:
        frames = replicate_image(file)
    else:
        return "Invalid file type", 0.0, plt.figure()

    if len(frames) < 10:
        return "Insufficient frames provided", 0.0, plt.figure()

    input_data = prepare_sequence(frames)

    try:
        prediction, attention_weights = model.predict(input_data)
    except:
        prediction = model.predict(input_data)
        attention_weights = np.zeros((1, 10, 1))

    probability = float(prediction[0][0])
    attention_weights = attention_weights.squeeze()

    if probability > 0.6:
        result_text = f"NOT  STRESSED (Confidence: {probability * 100:.2f}%)"
        confidence = probability
    elif probability < 0.4:
        result_text = f"STRESSED (Confidence: {(1 - probability) * 100:.2f}%)"
        confidence = 1 - probability
    else:
        result_text = f"UNCERTAIN / BALANCED (Confidence: {probability * 100:.2f}%)"
        confidence = probability

    fig = plt.figure(figsize=(15, 3))
    for i in range(10):
        plt.subplot(1, 10, i + 1)
        grayscale = cv2.cvtColor(frames[i], cv2.COLOR_BGR2GRAY)
        plt.imshow(grayscale, cmap='gray')
        plt.title(f"{attention_weights[i]:.2f}")
        plt.axis("off")
    plt.tight_layout()

    return result_text, float(confidence), fig

def create_gradio_interface():
    with gr.Blocks() as interface:
        gr.Markdown("## Real-Time Stress Detection Using Deep Learning and Attention Mechanism")
        gr.Markdown("Upload a short video (.mp4), a .zip file containing 10 images, or a single image for analysis.")

        file_input = gr.File(label="Upload Video / Image / Zip")
        prediction_output = gr.Textbox(label="Prediction Result")
        confidence_output = gr.Slider(0, 1, label="Confidence Level", interactive=False)
        attention_output = gr.Plot(label="Frame Attention Visualization")
        toggle_attention = gr.Checkbox(label="Display Attention Map", value=True)

        def run_prediction(file, show_map):
            label, score, plot = evaluate_input(file)
            return label, score, plot if show_map else plt.figure()

        predict_button = gr.Button("Run Analysis")
        predict_button.click(fn=run_prediction, inputs=[file_input, toggle_attention],
                             outputs=[prediction_output, confidence_output, attention_output])

    interface.launch()

if __name__ == "__main__":
    create_gradio_interface()

import os
import cv2
import zipfile
import shutil
import tempfile
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import gradio as gr

from temporal_model import build_temporal_model_with_attention

model = build_temporal_model_with_attention()
model.load_weights("best_model.h5")

def prepare_sequence(frames):
    processed_frames = []
    for frame in frames:
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        resized = cv2.resize(gray, (48, 48))
        normalized = resized.astype("float32") / 255.0
        processed_frames.append(np.expand_dims(normalized, axis=-1))
    return np.expand_dims(np.stack(processed_frames), axis=0)

def get_frames_from_video(video_path):
    cap = cv2.VideoCapture(video_path)
    frames = []
    while len(frames) < 10:
        ret, frame = cap.read()
        if not ret:
            break
        frames.append(frame)
    cap.release()
    while len(frames) < 10 and frames:
        frames.append(frames[-1])
    return frames[:10]

def extract_images_from_zip(zip_file):
    temp_dir = tempfile.mkdtemp()
    with zipfile.ZipFile(zip_file, 'r') as archive:
        archive.extractall(temp_dir)
    image_files = sorted([
        f for f in os.listdir(temp_dir)
        if f.lower().endswith(('.png', '.jpg', '.jpeg'))
    ])[:10]
    images = [cv2.imread(os.path.join(temp_dir, f)) for f in image_files]
    shutil.rmtree(temp_dir)
    return images

def replicate_image(image_path):
    image = cv2.imread(image_path.name if hasattr(image_path, 'name') else image_path)
    return [image] * 10

def evaluate_input(file):
    ext = os.path.splitext(file.name if hasattr(file, "name") else file)[-1].lower()

    if ext == ".zip":
        frames = extract_images_from_zip(file)
    elif ext in [".mp4", ".mov", ".avi"]:
        frames = get_frames_from_video(file)
    elif ext in [".png", ".jpg", ".jpeg"]:
        frames = replicate_image(file)
    else:
        return "Invalid file type", 0.0, plt.figure()

    if len(frames) < 10:
        return "Insufficient frames provided", 0.0, plt.figure()

    input_data = prepare_sequence(frames)

    try:
        prediction, attention_weights = model.predict(input_data)
    except:
        prediction = model.predict(input_data)
        attention_weights = np.zeros((1, 10, 1))

    probability = float(prediction[0][0])
    attention_weights = attention_weights.squeeze()

    if probability > 0.6:
        result_text = f"STRESSED (Confidence: {probability * 100:.2f}%)"
        confidence = probability
    elif probability < 0.4:
        result_text = f"NOT  STRESSED (Confidence: {(1 - probability) * 100:.2f}%)"
        confidence = 1 - probability
    else:
        result_text = f"UNCERTAIN / BALANCED (Confidence: {probability * 100:.2f}%)"
        confidence = probability

    fig = plt.figure(figsize=(15, 3))
    for i in range(10):
        plt.subplot(1, 10, i + 1)
        grayscale = cv2.cvtColor(frames[i], cv2.COLOR_BGR2GRAY)
        plt.imshow(grayscale, cmap='gray')
        plt.title(f"{attention_weights[i]:.2f}")
        plt.axis("off")
    plt.tight_layout()

    return result_text, float(confidence), fig

def create_gradio_interface():
    with gr.Blocks() as interface:
        gr.Markdown("## Real-Time Stress Detection Using Deep Learning and Attention Mechanism")
        gr.Markdown("Upload a short video (.mp4), a .zip file containing 10 images, or a single image for analysis.")

        file_input = gr.File(label="Upload Video / Image / Zip")
        prediction_output = gr.Textbox(label="Prediction Result")
        confidence_output = gr.Slider(0, 1, label="Confidence Level", interactive=False)
        attention_output = gr.Plot(label="Frame Attention Visualization")
        toggle_attention = gr.Checkbox(label="Display Attention Map", value=True)

        def run_prediction(file, show_map):
            label, score, plot = evaluate_input(file)
            return label, score, plot if show_map else plt.figure()

        predict_button = gr.Button("Run Analysis")
        predict_button.click(fn=run_prediction, inputs=[file_input, toggle_attention],
                             outputs=[prediction_output, confidence_output, attention_output])

    interface.launch()

if __name__ == "__main__":
    create_gradio_interface()

import zipfile

# Display the contents of the ZIP archive
with zipfile.ZipFile("/content/test_faces.zip", 'r') as zip_file:
    print("Contents of the ZIP archive:")
    for file_name in zip_file.namelist():
        print(" └──", file_name)

from google.colab import files
files.download("/content/test_faces.zip")

import matplotlib.pyplot as plt
from PIL import Image
import os
import zipfile

# Extract images from the ZIP archive
with zipfile.ZipFile("/content/test_faces.zip", 'r') as archive:
    archive.extractall("/content/temp_test_images")

# List and sort the extracted image files
image_files = sorted(os.listdir("/content/temp_test_images"))

# Display the images in a single row of subplots
plt.figure(figsize=(15, 2))
for idx, filename in enumerate(image_files):
    image_path = os.path.join("/content/temp_test_images", filename)
    image = Image.open(image_path)
    plt.subplot(1, 10, idx + 1)
    plt.imshow(image, cmap='gray')
    plt.title(filename.split('.')[0])
    plt.axis("off")

plt.suptitle("Preview of Images from ZIP Archive", fontsize=16)
plt.tight_layout()
plt.show()

